# 此工作流将在向“main”分支推送代码时，构建并推送一个新的容器镜像至阿里云容器镜像服务（ACR），
# 随后将其部署到阿里云容器服务Kubernetes版（ACK）。
#
# 要使用此工作流，您需要完成以下设置步骤：
#
# 1. 创建一个 ACR 仓库，用于存储您的容器镜像。
# 您可以使用 ACR EE 实例，以获得更高的安全性和更优的性能。
# 有关说明请参见 https://www.alibabacloud.com/help/doc-detail/142168.htm
#
# 2. 创建一个 ACK 集群，用于运行您的容器化应用。
# 您可以使用 ACK Pro 集群，以获得更高的安全性与更优的性能。
# 有关说明请参见 https://www.alibabacloud.com/help/doc-detail/95108.htm
#
# 3. 将您的 AccessKey 密钥对存储在 GitHub Actions 的名为 `ACCESS_KEY_ID` 和 `ACCESS_KEY_SECRET` 的密钥中。
# 有关设置机密的说明，请参阅：https://developer.github.com/actions/managing-workflows/storing-secrets/
#
# 4. 修改 REGION_ID、REGISTRY、NAMESPACE、IMAGE、ACK_CLUSTER_ID 和 ACK_DEPLOYMENT_NAME 的值。
#

名称: 构建并部署到 ACK

:
:
: [ "main" ]


环境:
 区域ID: cn-hangzhou
注册表: registry.cn-hangzhou.aliyuncs.com
: 命名空间
: 仓库
: ${{ github.sha }}
: clusterID
: nginx-deployment

: myregistry.cn-hangzhou.cr.aliyuncs.com
  ACR_EE_INSTANCE_ID: instanceID
  ACR_EE_NAMESPACE: 命名空间
  ACR_EE_IMAGE: 仓库
  ACR_EE_TAG: ${{ github.sha }}

权限:
  内容: 读取

作业:
  构建:
    运行环境: ubuntu-latest
    环境: 生产环境

步骤:
    - 名称: 检出代码
      用途: actions/checkout@v4

    # 1.1 登录 ACR
    - 名称: 使用AccessKey对ACR进行登录
      用途: aliyun/acr-login@v1
      with:
        区域ID: "${{ env.REGION_ID }}"
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"

    # 1.2 Build and push image to ACR
    - name: Build and push image to ACR
      run: |
        docker build --tag "$REGISTRY/$NAMESPACE/$IMAGE:$TAG" .
        docker push "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"

    # 1.3 Scan image in ACR
    - name: Scan image in ACR
      uses: aliyun/acr-scan@v1
      with:
        区域ID: "${{ env.REGION_ID }}"
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
        仓库: "${{ env.NAMESPACE }}/${{ env.IMAGE }}"
        标签: "${{ env.TAG }}"

    # 2.1 (Optional) Login to ACR EE
    - uses: actions/checkout@v4
    - name: Login to ACR EE with the AccessKey pair
      uses: aliyun/acr-login@v1
      with:
        login-server: "https://${{ env.ACR_EE_REGISTRY }}"
        region-id: "${{ env.REGION_ID }}"
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
        instance-id: "${{ env.ACR_EE_INSTANCE_ID }}"

    # 2.2 (Optional) Build and push image ACR EE
    - name: Build and push image to ACR EE
      run: |
        docker build -t "$ACR_EE_REGISTRY/$ACR_EE_NAMESPACE/$ACR_EE_IMAGE:$TAG" .
        docker push "$ACR_EE_REGISTRY/$ACR_EE_NAMESPACE/$ACR_EE_IMAGE:$TAG"
    # 2.3 (Optional) Scan image in ACR EE
    - name: Scan image in ACR EE
      uses: aliyun/acr-scan@v1
      with:
        区域ID: "${{ env.REGION_ID }}"
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
        实例ID: "${{ env.ACR_EE_INSTANCE_ID }}"
        仓库: "${{ env.ACR_EE_NAMESPACE}}/${{ env.ACR_EE_IMAGE }}"
        标签: "${{ env.ACR_EE_TAG }}"

    # 3.1 设置 ACK 上下文
    - 名称: 设置 K8s 上下文
      使用: aliyun/ack-set-context@v1
      with:
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
        cluster-id: "${{ env.ACK_CLUSTER_ID }}"

    # 3.2 Deploy the image to the ACK cluster
    - name: Set up Kustomize
      run: |-
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash /dev/stdin 3.8.6
    - name: Deploy
      run: |-
        ./kustomize edit set image REGISTRY/NAMESPACE/IMAGE:TAG=$REGISTRY/$NAMESPACE/$IMAGE:$TAG
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$ACK_DEPLOYMENT_NAME
        kubectl get services -o wide
